# GoReleaser configuration
# https://goreleaser.com/

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: manage-agent-skills
    binary: manage-agent-skills
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore windows/arm64 combination as it's not commonly used
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      # -s -w: Strip debug information and symbol table to reduce binary size
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      # Include default config.toml as a template (users customize at ~/.config/manage-agent-skills/config.toml)
      - config.toml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: tsubasaogawa
    name: manage-agent-skills
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    ## Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### Using go install
    
    ```bash
    go install github.com/tsubasaogawa/manage-agent-skills@{{ .Tag }}
    ```
